import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,STORAGE_KEY} from '../dist/workspace.js';
import {library} from '../dist/data.js';
const memory=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};};
test('ready-made saves are deduplicated and survive reopening',()=>{const disk=memory(),w=createWorkspace(disk);w.saveLibrary('balanced');w.saveLibrary('balanced');assert.equal(w.state.savedScanners.length,1);assert.equal(createWorkspace(disk).state.savedScanners[0].sourceId,'balanced');});
test('draft survives reload with all criteria, including disabled checks',()=>{const disk=memory(),w=createWorkspace(disk);w.beginDraft({mode:'customize',scanner:library[1]});w.updateDraft({name:'My watch',age:'At least 30 days',concentration:false});w.step(2);const loaded=createWorkspace(disk);assert.equal(loaded.state.draft.fields.name,'My watch');assert.equal(loaded.state.draft.fields.age,'At least 30 days');assert.equal(loaded.state.draft.fields.concentration,false);assert.equal(loaded.state.draft.step,2);});
test('editing a draft never mutates saved rules before Save',()=>{const w=createWorkspace(memory()),s=w.saveLibrary('balanced').scanner;w.beginDraft({mode:'edit',scanner:s});w.updateDraft({name:'Different',age:'At least 90 days'});assert.equal(w.state.savedScanners[0].name,'Public figure scanner');w.discardDraft();assert.equal(w.state.savedScanners[0].age,'Any age');});
test('editing a library instance and adding original keeps unique ids and both records',()=>{const w=createWorkspace(memory()),original=w.saveLibrary('balanced').scanner;w.beginDraft({mode:'edit',scanner:original});w.updateDraft({name:'My copy',filters:{...w.state.draft.fields.filters,accounts:'@example'}});const custom=w.saveDraft().scanner;const newOriginal=w.saveLibrary('balanced').scanner;assert.notEqual(custom.id,newOriginal.id);assert.equal(w.state.savedScanners.length,2);w.remove(custom.id);assert.equal(w.state.savedScanners.length,1);assert.equal(w.state.savedScanners[0].name,'Public figure scanner');w.undo();assert.equal(w.state.savedScanners.length,2);});
test('personal scanner edit keeps no invented catalog attribution',()=>{const w=createWorkspace(memory());w.beginDraft();const s=w.saveDraft().scanner;w.beginDraft({mode:'edit',scanner:s});assert.equal(w.state.draft.sourceId,null);});
test('customization preserves source and original defaults',()=>{const w=createWorkspace(memory());w.beginDraft({mode:'customize',scanner:library[0]});w.updateDraft({liquidity:'Any liquidity',filters:{...w.state.draft.fields.filters,accounts:'@example'}});const s=w.saveDraft().scanner;assert.equal(s.sourceId,'balanced');assert.equal(library[0].criteria.liquidity,'Established');});
test('blank names cannot save',()=>{const w=createWorkspace(memory());w.beginDraft();w.updateDraft({name:'  '});assert.equal(w.saveDraft(),null);assert.equal(w.state.savedScanners.length,0);});
test('remove and undo remain available after reopening',()=>{const disk=memory(),w=createWorkspace(disk);const s=w.saveLibrary('momentum').scanner;w.remove(s.id);const loaded=createWorkspace(disk);assert.equal(loaded.state.savedScanners.length,0);assert.equal(loaded.undo().id,s.id);assert.equal(loaded.state.savedScanners.length,1);});
test('storage write failure retains in-memory work and can retry',()=>{const disk=memory();let fail=true;const store={getItem:disk.getItem,setItem:(k,v)=>{if(fail)throw Error('Quota');disk.setItem(k,v);}};const w=createWorkspace(store);const result=w.saveLibrary('balanced');assert.equal(result.persisted,false);assert.equal(w.issue,'write');assert.equal(w.state.savedScanners.length,1);fail=false;assert.equal(w.retry(),true);assert.equal(w.issue,null);assert.equal(createWorkspace(store).state.savedScanners.length,1);});
test('unreadable saved data is not overwritten',()=>{const disk=memory();disk.setItem(STORAGE_KEY,'broken data');const w=createWorkspace(disk);w.saveLibrary('balanced');assert.equal(w.issue,'read');assert.equal(disk.getItem(STORAGE_KEY),'broken data');assert.equal(JSON.parse(w.export()).savedScanners.length,1);});

test('new workspaces stay empty until a scanner is explicitly added',()=>{const disk=memory(),w=createWorkspace(disk);w.prepareWorkspace();assert.equal(w.state.savedScanners.length,0);const reopened=createWorkspace(disk);reopened.prepareWorkspace();assert.equal(reopened.state.savedScanners.length,0);const active=reopened.saveLibrary('balanced').scanner;const saved=reopened.saveLibrary('momentum','saved').scanner;const loaded=createWorkspace(disk);loaded.prepareWorkspace();assert.deepEqual(loaded.state.savedScanners.map(s=>[s.id,s.placement]),[[active.id,'active'],[saved.id,'saved']]);});
test('starter setup preserves personal work and unfinished drafts',()=>{const w=createWorkspace(memory());w.beginDraft();w.updateDraft({name:'Personal work'});w.saveDraft();w.beginDraft();w.updateDraft({name:'Unfinished'});w.prepareWorkspace();assert.equal(w.state.savedScanners.length,1);assert.equal(w.state.savedScanners[0].name,'Personal work');assert.equal(w.state.draft.fields.name,'Unfinished');});
test('starter setup renames only unchanged library defaults',()=>{const disk=memory(),w=createWorkspace(disk);w.saveLibrary('balanced');const old=JSON.parse(w.export());old.savedScanners[0].name='Balanced discovery';disk.setItem(STORAGE_KEY,JSON.stringify(old));const reopened=createWorkspace(disk);reopened.prepareWorkspace();assert.equal(reopened.state.savedScanners[0].name,'Public figure scanner');assert.equal(reopened.state.savedScanners.length,1);});

test('legacy scanner placement defaults to active without changing work',()=>{const disk=memory(),w=createWorkspace(disk);const scanner=w.saveLibrary('balanced').scanner;w.beginDraft({mode:'edit',scanner});w.updateDraft({name:'Unfinished edits',liquidity:'Higher liquidity'});w.remove(scanner.id);const legacy=JSON.parse(w.export());delete legacy.removed.placement;disk.setItem(STORAGE_KEY,JSON.stringify(legacy));const loaded=createWorkspace(disk);const restored=loaded.undo();assert.equal(restored.placement,'active');assert.equal(restored.id,scanner.id);assert.equal(loaded.state.draft.fields.name,'Unfinished edits');assert.equal(loaded.state.draft.fields.liquidity,'Higher liquidity');});

test('saved-for-later placement survives activation, editing and reload without duplication',()=>{const disk=memory(),w=createWorkspace(disk);const s=w.saveLibrary('liquidity','saved').scanner;assert.equal(createWorkspace(disk).state.savedScanners[0].placement,'saved');assert.equal(w.saveLibrary('liquidity').scanner.id,s.id);w.move(s.id,'active');w.beginDraft({mode:'edit',scanner:s});w.updateDraft({name:'My liquidity rules',age:'At least 90 days'});w.saveDraft();w.move(s.id,'saved');w.beginDraft({mode:'edit',scanner:w.state.savedScanners[0]});w.updateDraft({description:'Keep for later'});w.saveDraft();const loaded=createWorkspace(disk);assert.equal(loaded.state.savedScanners.length,1);assert.equal(loaded.state.savedScanners[0].id,s.id);assert.equal(loaded.state.savedScanners[0].placement,'saved');assert.equal(loaded.state.savedScanners[0].age,'At least 90 days');assert.equal(loaded.state.savedScanners[0].description,'Keep for later');});

test('empty active list does not reseed and undo preserves saved placement',()=>{const disk=memory(),w=createWorkspace(disk);w.prepareWorkspace();w.saveLibrary('balanced');w.saveLibrary('momentum');for(const s of w.state.savedScanners)w.move(s.id,'saved');const id=w.state.savedScanners[0].id;w.remove(id);const loaded=createWorkspace(disk);loaded.prepareWorkspace();assert.equal(loaded.state.savedScanners.filter(s=>s.placement==='active').length,0);const restored=loaded.undo();assert.equal(restored.placement,'saved');assert.equal(restored.id,id);assert.equal(loaded.state.savedScanners.length,2);});

test('retired creator filters reset while existing scanners and drafts remain intact',()=>{const disk=memory(),w=createWorkspace(disk);const scanner=w.saveLibrary('conviction','saved').scanner;w.beginDraft({mode:'edit',scanner});w.updateDraft({name:'My older projects'});w.setView({filter:'creators',selected:'conviction'});const loaded=createWorkspace(disk);assert.equal(loaded.state.view.filter,'all');assert.equal(loaded.state.savedScanners[0].id,scanner.id);assert.equal(loaded.state.savedScanners[0].sourceId,'conviction');assert.equal(loaded.state.savedScanners[0].placement,'saved');assert.equal(loaded.state.draft.fields.name,'My older projects');assert.equal(loaded.state.draft.sourceId,'conviction');loaded.setView({filter:'new-projects'});assert.equal(createWorkspace(disk).state.view.filter,'all');});
